apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-device-plugin-timeslicing
  namespace: kube-system
data:
  default: |-
    version: v1
    flags:
      migStrategy: none
    sharing:
      timeSlicing:
        renameByDefault: false
        failRequestsGreaterThanOne: true
        resources:
          - name: nvidia.com/gpu
            replicas: 4
