apiVersion: apps.nvidia.com/v1alpha1
kind: NIMCache
metadata:
  name: llama31-8b-instruct-fixed-cache
spec:
  nodeSelector:
    workload: gpu-fixed
  tolerations:
    - key: nvidia.com/gpu
      operator: Equal
      value: "true"
      effect: NoSchedule
  source:
    ngc:
      modelPuller: nvcr.io/nim/meta/llama-3.1-8b-instruct:2.0.3
      pullSecret: ngc-secret
      authSecret: ngc-api-secret
      model:
        engine: vllm
        tensorParallelism: "1"
        profiles:
          - a28963301b18077db3454d5eb21f5678304936c5a425ddc552443de1f5449f2a
  storage:
    pvc:
      create: true
      storageClass: efs-sc-nim
      size: 30Gi
      volumeAccessMode: ReadWriteMany
