apiVersion: apps.nvidia.com/v1alpha1
kind: NIMService
metadata:
  name: llama31-8b-instruct-fixed
  labels:
    app.kubernetes.io/name: nim
    app.kubernetes.io/instance: llama31-8b-instruct-fixed
    app.kubernetes.io/component: inference
    app.kubernetes.io/part-of: demo-examples
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  image:
    repository: nvcr.io/nim/meta/llama-3.1-8b-instruct
    tag: "2.0.3"
    pullPolicy: IfNotPresent
    pullSecrets:
      - ngc-secret
  authSecret: ngc-api-secret
  env:
    - name: NIM_MAX_MODEL_LEN
      value: "32768"
  storage:
    nimCache:
      name: llama31-8b-instruct-fixed-cache
      profile: "a28963301b18077db3454d5eb21f5678304936c5a425ddc552443de1f5449f2a"
    readOnly: false
  nodeSelector:
    workload: gpu-fixed
  tolerations:
    - key: nvidia.com/gpu
      operator: Equal
      value: "true"
      effect: NoSchedule
  resources:
    requests:
      cpu: "4"
      memory: "16Gi"
      nvidia.com/gpu: "1"
    limits:
      cpu: "8"
      memory: "24Gi"
      nvidia.com/gpu: "1"
  replicas: 1
  expose:
    service:
      type: ClusterIP
      port: 8000
